# Generated by Django 3.1 on 2020-12-07 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zoning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('code', models.CharField(max_length=32, verbose_name='编码')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='行政级别')),
                ('prefix', models.CharField(max_length=8, null=True, verbose_name='区号')),
                ('post_code', models.CharField(max_length=8, null=True, verbose_name='邮政编号')),
                ('abbreviation', models.CharField(max_length=8, null=True, verbose_name='简称')),
                ('administrative_center', models.CharField(max_length=32, null=True, verbose_name='行政中心')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoning.zoning')),
            ],
            options={
                'db_table': 'zoning',
            },
        ),
    ]
