# Generated by Django 3.0 on 2020-07-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='文件名称')),
                ('path', models.CharField(max_length=128, verbose_name='文件链接')),
                ('type', models.CharField(max_length=8, null=True, verbose_name='文件类型')),
                ('size', models.CharField(max_length=8, null=True, verbose_name='文件大小')),
                ('note', models.TextField(default='', verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'file_server',
            },
        ),
    ]
